version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "666:8080"
    volumes:
      - .:/go/src/app
    depends_on:
      - db

  redis:
    image: redis:6.0.9
    volumes:
      - auth_redis_data:/data

  db:
    image: postgres:12
    container_name: postgres
    ports:
      - "45487:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: 'fortestpwd'
      POSTGRES_DB: auth
    shm_size: 512mb

volumes:
  postgres_data:
  auth_redis_data:
