version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "666:8080"

  db:
    image: postgres:12
    container_name: postgres
    ports:
      - "45487:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: 'fortestpwd'
      POSTGRES_DB: auth
    shm_size: 512mb

volumes:
  postgres_data:
