version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "666:8080"
    volumes:
      - .:/go/src/app
    depends_on:
      - db

  redis:
    image: redis:6.0.9
    volumes:
      - auth_redis_data:/data

  db:
    image: postgres:12
    container_name: postgres
    ports:
      - "45487:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: 'fortestpwd'
      POSTGRES_DB: auth
    shm_size: 512mb
    healthcheck:
      test: [
          "CMD-SHELL",
          "pg_isready -U postgres && psql -U postgres -lqt | cut -d \\| -f 1 | grep auth || exit 1"
      ]
      interval: 30s
      timeout: 10s
      retries: 10

  tracing:
    image: jaegertracing/all-in-one:1
    ports:
      - "5775:5776/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
    depends_on:
      - app

volumes:
  postgres_data:
  auth_redis_data:
