version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "666:8080"
    volumes:
      - .:/go/src/app
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:12
    container_name: postgres
    ports:
      - "45487:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: 'fortestpwd'
#      POSTGRES_DB: auth
      POSTGRES_MULTIPLE_DATABASES: auth, auth_test
    shm_size: 512mb
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
