// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/email/register": {
            "post": {
                "description": "Using email to register an account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "E-mail"
                ],
                "summary": "Register an account by email",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers_v1.RegisterByMailInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"msg\":ok}",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseContent"
                        }
                    },
                    "400": {
                        "description": "40022:validation failed, 400009: already registered",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseContent"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        },
        "/api/v1/email/verify": {
            "post": {
                "description": "Using email to receive a login token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "E-mail"
                ],
                "summary": "Get login token by email",
                "parameters": [
                    {
                        "description": "login data",
                        "name": "JSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers_v1.VerifyMailLoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":200, \"msg\":ok}",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseContent"
                        }
                    },
                    "400": {
                        "description": "40004:user not found, 40000: email not verified yet",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseContent"
                        }
                    },
                    "500": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers_v1.RegisterByMailInput": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "dean.test@gmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "dean"
                },
                "password": {
                    "type": "string",
                    "example": "!AS$GK())"
                }
            }
        },
        "handlers_v1.VerifyMailLoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "dean.test@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "!AS$GK())"
                }
            }
        },
        "helpers.ResponseContent": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "object"
                },
                "msg": {
                    "type": "string",
                    "example": "ok"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
